// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoHsj_alpha.Models;

#nullable disable

namespace ProyectoHsj_alpha.Migrations
{
    [DbContext(typeof(HoySeJuegaContext))]
    partial class HoySeJuegaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_rol");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int")
                        .HasColumnName("ID_permiso");

                    b.HasKey("IdRol", "IdPermiso")
                        .HasName("PK__PERMISO___9F614A338C7DB628");

                    b.HasIndex("IdPermiso");

                    b.ToTable("PERMISO_ROL", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Auditorium", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .HasColumnType("int")
                        .HasColumnName("ID_auditoria");

                    b.Property<string>("AccionRealizada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Accion_Realizada");

                    b.Property<string>("DescripcionDeAccion")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Descripcion_De_Accion");

                    b.Property<DateTime>("FechaAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Auditoria")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.HasKey("IdAuditoria")
                        .HasName("PK__AUDITORI__F6FFFB8CD089E2B5");

                    b.HasIndex("IdUsuario");

                    b.ToTable("AUDITORIA", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Cancha", b =>
                {
                    b.Property<int>("IdCancha")
                        .HasColumnType("int")
                        .HasColumnName("ID_cancha");

                    b.Property<string>("NombreCancha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Nombre_Cancha");

                    b.Property<string>("UbicacionCancha")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Ubicacion_Cancha");

                    b.HasKey("IdCancha")
                        .HasName("PK__CANCHA__A2D3DBCF31AC53D9");

                    b.ToTable("CANCHA", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.EstadoReserva", b =>
                {
                    b.Property<int>("IdEstadoReserva")
                        .HasColumnType("int")
                        .HasColumnName("ID_estado_reserva");

                    b.Property<string>("NombreEstadoReserva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Nombre_Estado_Reserva");

                    b.HasKey("IdEstadoReserva")
                        .HasName("PK__ESTADO_R__746A84F0163347B6");

                    b.ToTable("ESTADO_RESERVA", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.HorarioDisponible", b =>
                {
                    b.Property<int>("IdHorarioDisponible")
                        .HasColumnType("int")
                        .HasColumnName("ID_horario_disponible");

                    b.Property<bool?>("DisponibleHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Disponible_Horario");

                    b.Property<DateOnly>("FechaHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Horario")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Inicio");

                    b.Property<int>("IdCancha")
                        .HasColumnType("int")
                        .HasColumnName("ID_cancha");

                    b.HasKey("IdHorarioDisponible")
                        .HasName("PK__HORARIO___7D5601B713FD2B44");

                    b.HasIndex("IdCancha");

                    b.ToTable("HORARIO_DISPONIBLE", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_notificacion");

                    b.Property<DateTime>("FechaEnvioNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Envio_Notificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("ID_reserva");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.Property<string>("MensajeNotificacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Mensaje_Notificacion");

                    b.Property<string>("TituloNotificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Titulo_Notificacion");

                    b.HasKey("IdNotificacion")
                        .HasName("PK__NOTIFICA__99BC7E5EE9FDA64F");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdUsuario");

                    b.ToTable("NOTIFICACION", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("ID_pago");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Pago")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("ID_reserva");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Monto_Pago");

                    b.HasKey("IdPago")
                        .HasName("PK__PAGO__808903ECD6745E92");

                    b.HasIndex("IdReserva");

                    b.ToTable("PAGO", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .HasColumnType("int")
                        .HasColumnName("ID_permiso");

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Nombre_Permiso");

                    b.HasKey("IdPermiso")
                        .HasName("PK__PERMISO__74B1E2192888FD4F");

                    b.ToTable("PERMISO", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .HasColumnType("int")
                        .HasColumnName("ID_reporte");

                    b.Property<int>("AnioReporte")
                        .HasColumnType("int")
                        .HasColumnName("Anio_Reporte");

                    b.Property<DateTime>("FechaDeReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_De_Reporte")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte>("MesReporte")
                        .HasColumnType("tinyint")
                        .HasColumnName("Mes_Reporte");

                    b.Property<int?>("ReservasRealizadasReporte")
                        .HasColumnType("int")
                        .HasColumnName("Reservas_Realizadas_Reporte");

                    b.Property<int?>("UsuariosRegistradosReporte")
                        .HasColumnType("int")
                        .HasColumnName("Usuarios_Registrados_Reporte");

                    b.HasKey("IdReporte")
                        .HasName("PK__REPORTE__41AEEB64EA3D5483");

                    b.ToTable("REPORTE", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("ID_reserva");

                    b.Property<DateOnly>("FechaReserva")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Reserva");

                    b.Property<int>("IdCancha")
                        .HasColumnType("int")
                        .HasColumnName("ID_cancha");

                    b.Property<int>("IdEstadoReserva")
                        .HasColumnType("int")
                        .HasColumnName("ID_estado_reserva");

                    b.Property<int>("IdHorarioDisponible")
                        .HasColumnType("int")
                        .HasColumnName("ID_horario_disponible");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.HasKey("IdReserva")
                        .HasName("PK__RESERVA__CD692CB04CD77469");

                    b.HasIndex("IdCancha");

                    b.HasIndex("IdEstadoReserva");

                    b.HasIndex("IdHorarioDisponible");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RESERVA", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_rol");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Nombre_Rol");

                    b.HasKey("IdRol")
                        .HasName("PK__ROL__182A5412735EDC29");

                    b.ToTable("ROL", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.Property<string>("ApellidoUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Apellido_Usuario");

                    b.Property<string>("ContraseniaUsuario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Contrasenia_Usuario");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Correo_Usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_rol");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Nombre_Usuario");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("TelefonoUsuario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Telefono_Usuario");

                    b.HasKey("IdUsuario")
                        .HasName("PK__USUARIO__DF3D4252EC4CA997");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "CorreoUsuario" }, "UQ__USUARIO__A71263111919BEEC")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.HasOne("ProyectoHsj_alpha.Models.Permiso", null)
                        .WithMany()
                        .HasForeignKey("IdPermiso")
                        .IsRequired()
                        .HasConstraintName("FK__PERMISO_R__ID_pe__4222D4EF");

                    b.HasOne("ProyectoHsj_alpha.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__PERMISO_R__ID_ro__4316F928");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Auditorium", b =>
                {
                    b.HasOne("ProyectoHsj_alpha.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Auditoria")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__AUDITORIA__ID_us__46E78A0C");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.HorarioDisponible", b =>
                {
                    b.HasOne("ProyectoHsj_alpha.Models.Cancha", "IdCanchaNavigation")
                        .WithMany("HorarioDisponibles")
                        .HasForeignKey("IdCancha")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_D__ID_ca__4D94879B");

                    b.Navigation("IdCanchaNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Notificacion", b =>
                {
                    b.HasOne("ProyectoHsj_alpha.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Notificacions")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK__NOTIFICAC__ID_re__5DCAEF64");

                    b.HasOne("ProyectoHsj_alpha.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Notificacions")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__NOTIFICAC__ID_us__5CD6CB2B");

                    b.Navigation("IdReservaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Pago", b =>
                {
                    b.HasOne("ProyectoHsj_alpha.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK__PAGO__ID_reserva__59063A47");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Reserva", b =>
                {
                    b.HasOne("ProyectoHsj_alpha.Models.Cancha", "IdCanchaNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCancha")
                        .IsRequired()
                        .HasConstraintName("FK__RESERVA__ID_canc__5441852A");

                    b.HasOne("ProyectoHsj_alpha.Models.EstadoReserva", "IdEstadoReservaNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEstadoReserva")
                        .IsRequired()
                        .HasConstraintName("FK__RESERVA__ID_esta__52593CB8");

                    b.HasOne("ProyectoHsj_alpha.Models.HorarioDisponible", "IdHorarioDisponibleNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdHorarioDisponible")
                        .IsRequired()
                        .HasConstraintName("FK__RESERVA__ID_hora__5535A963");

                    b.HasOne("ProyectoHsj_alpha.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__RESERVA__ID_usua__534D60F1");

                    b.Navigation("IdCanchaNavigation");

                    b.Navigation("IdEstadoReservaNavigation");

                    b.Navigation("IdHorarioDisponibleNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoHsj_alpha.Models.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__USUARIO__ID_rol__3D5E1FD2");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Cancha", b =>
                {
                    b.Navigation("HorarioDisponibles");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.EstadoReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.HorarioDisponible", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Reserva", b =>
                {
                    b.Navigation("Notificacions");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProyectoHsj_alpha.Models.Usuario", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("Notificacions");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
